version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db_myapp1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp1_development
    networks:
      - default
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  web:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: web_myapp1
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      TZ: Asia/Tokyo
    networks:
      - default
    ports:
      - '3000:3000'
    volumes:
      - .:/myapp1
    depends_on:
      - db
    command: bundle exec rails server -b 0.0.0.0
volumes:
  mysql_data:
    driver: local
