version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db_myapp1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp1_development
    networks:
      - default
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome_myapp1
    ports:
      - '4444:4444'
  web:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: web_myapp1
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      TZ: Asia/Tokyo
    networks:
      - default
    ports:
      - '3000:3000'
    depends_on:
      - db
      - chrome
    command: bundle exec rails server -b 0.0.0.0
